var adabas = require('adabas');

console.log("[1] Create Adabas command.");
var query = new adabas.Command();
console.log(query.toString());

console.log("[2] Set fields of Adabas control block.");
query.set(adabas.COMMAND_CODE, 'L1');
query.set(adabas.COMMAND_ID, 'TEST');
query.set(adabas.DB_ID, 88);
query.set(adabas.FILE_NO, 12);
query.set(adabas.RETURN_CODE, 1);
query.set(adabas.ISN, 10);
query.set(adabas.ISN_LOWER_LIMIT, 20);
query.set(adabas.ISN_QUANTITY, 30);
query.set(adabas.FORMAT_BUFFER_LENGTH, 1000);
query.set(adabas.RECORD_BUFFER_LENGTH, 2000);
query.set(adabas.SEARCH_BUFFER_LENGTH, 3000);
query.set(adabas.VALUE_BUFFER_LENGTH, 4000);
query.set(adabas.ISN_BUFFER_LENGTH, 5000);
query.set(adabas.COMMAND_OPTION1, 65);
query.set(adabas.COMMAND_OPTION2, 66);
query.set(adabas.ADDITION1, [1, 1, 1, 1, 1, 1, 1, 1]);
query.set(adabas.ADDITION2, [1, 2, 3, 4]);
query.set(adabas.ADDITION3, [0, 1, 2, 3, 4, 5, 6, 7]);
query.set(adabas.ADDITION4, [7, 6, 5, 4, 3, 2, 1, 0]);
query.set(adabas.ADDITION5, [10, 20, 30, 40, 50, 60, 70, 80]);
query.set(adabas.COMMAND_TIME, 12345);
query.set(adabas.USER_AREA, [1, 2, 3, 4]);
console.log(query.toString());

console.log("[3] Get fields of Adabas control block.");
console.log("Command Code     :", query.get(adabas.COMMAND_CODE));
console.log("Command Id       :", query.get(adabas.COMMAND_ID));
console.log("File Number      :", query.get(adabas.FILE_NO));
console.log("Database Id      :", query.get(adabas.DB_ID));
console.log("Response Code    :", query.get(adabas.RETURN_CODE));
console.log("Isn              :", query.get(adabas.ISN));
console.log("Isn Lower Limit  :", query.get(adabas.ISN_LOWER_LIMIT));
console.log("Isn Quantity     :", query.get(adabas.ISN_QUANTITY));
console.log("FB Length        :", query.get(adabas.FORMAT_BUFFER_LENGTH));
console.log("RB Length        :", query.get(adabas.RECORD_BUFFER_LENGTH));
console.log("SB Length        :", query.get(adabas.SEARCH_BUFFER_LENGTH));
console.log("VB Length        :", query.get(adabas.VALUE_BUFFER_LENGTH));
console.log("IB Length        :", query.get(adabas.ISN_BUFFER_LENGTH));
console.log("Command Option 1 :", query.get(adabas.COMMAND_OPTION1));
console.log("Command Option 2 :", query.get(adabas.COMMAND_OPTION2));
console.log("Additions 1      :", query.get(adabas.ADDITION1));
console.log("Additions 2      :", query.get(adabas.ADDITION2));
console.log("Additions 3      :", query.get(adabas.ADDITION3));
console.log("Additions 4      :", query.get(adabas.ADDITION4));
console.log("Additions 5      :", query.get(adabas.ADDITION5));
console.log("Command Time     :", query.get(adabas.COMMAND_TIME));
console.log("User Area        :", query.get(adabas.USER_AREA));
